name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
    tags-ignore:
      # This will ignore release versions tagged with a version identifier. We'll 
      # use a separate workflow for them.
      - 'v*'
  pull_request:
    paths-ignore: 
      - README.md

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x

    - name: Build for RimWorld 1.2
      run: dotnet build --configuration RW12Release

    - name: Build for RimWorld 1.3
      run: dotnet build --configuration RW13Release

    - name: Test Mod
      run: dotnet test --verbosity normal
