name: Build

on:
  push:
    tags:
      # This will only run the release workflow when it's tagged with a version
      # tag.
      - 'v*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build for RimWorld 1.2
      run: dotnet build --configuration RW12Release

    - name: Build for RimWorld 1.3
      run: dotnet build --configuration RW13Release

    - name: Test Mod
      run: dotnet test --verbosity normal

    - name: Zip Mod
      run: zip -r RWP About/ 1.2/ 1.3/ Common/ LICENSE THIRD-PARTY-NOTICES.txt

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "RWP.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
